### PR TITLE
RuntimeSimplifier behaviour like UnityMeshSimplifier, tasks and optim…

### PR DESCRIPTION
**Pull request by ValeryPopov1995**
Hi! Thanks for the convenient way to optimize meshes in games! I am using your repository for my test work and have made some changes. Will you take a look?
I think it will work more optimally and user-friendly. The number of lines has decreased, which is more convenient for navigation.
I made a couple of additional demoscenes and brought the logic into a user-friendly class.

### CODE REVIEW

**Review by simplestargame — APPROVED** [review]
LGTM

It has become a very easy-to-use tool, hasn't it? I've tried all the samples, and there are no issues.

**Comment by ValeryPopov1995** [comment]
Yes! Thanks for the approved pull request, thanks for the handy tool.

сб, 17 февр. 2024 г., 12:48 simplestar-game ***@***.***>:

**Comment by ValeryPopov1995** [comment]
Hello!
In February, I really wanted to contribute to your useful RuntimeSimplifier tool)
I have just discovered that the case has not been completed. Can the pull request<https://github.com/simplestargame/RuntimeMeshSimplification/pull/1> be accepted?
________________________________
От: Valery Popov ***@***.***>
Отправлено: 19 февраля 2024 г. 21:20
Кому: simplestargame/RuntimeMeshSimplification ***@***.***>
Тема: Re: [simplestargame/RuntimeMeshSimplification] RuntimeSimplifier behaviour like UnityMeshSimplifier, tasks and optim… (PR #1)

Yes! Thanks for the approved pull request, thanks for the handy tool.

сб, 17 февр. 2024 г., 12:48 simplestar-game ***@***.******@***.***>>:

@simplestargame approved this pull request.

LGTM

It has become a very easy-to-use tool, hasn't it? I've tried all the samples, and there are no issues.

**Comment by simplestargame** [comment]
I apologize for the long wait. The pull request has been merged.

**Comment by ValeryPopov1995** [comment]
Thanks for the good asset! Thank you for allowing me to contribute to it!
________________________________
От: simplestar-game ***@***.***>
Отправлено: 17 апреля 2024 г. 14:16
Кому: simplestargame/RuntimeMeshSimplification ***@***.***>
Копия: Valery Popov ***@***.***>; Author ***@***.***>
Тема: Re: [simplestargame/RuntimeMeshSimplification] RuntimeSimplifier behaviour like UnityMeshSimplifier, tasks and optim… (PR #1)


Merged #1<https://github.com/simplestargame/RuntimeMeshSimplification/pull/1> into main.

**Comment by ValeryPopov1995** [comment]
Thanks! We will move on)
________________________________
От: simplestar-game ***@***.***>
Отправлено: 17 апреля 2024 г. 14:18
Кому: simplestargame/RuntimeMeshSimplification ***@***.***>
Копия: Valery Popov ***@***.***>; Author ***@***.***>
Тема: Re: [simplestargame/RuntimeMeshSimplification] RuntimeSimplifier behaviour like UnityMeshSimplifier, tasks and optim… (PR #1)


I apologize for the long wait. The pull request has been merged.

**Pull request merged**
